local _, loadingAddonNamespace = ...;
---@type LibAddonProfilesPrivate
local private = loadingAddonNamespace.GetLibAddonProfilesInternal and loadingAddonNamespace:GetLibAddonProfilesInternal();
if (not private) then return; end

---@class RefreshHook : table
---@field tableFunc fun() : table The target table that we want to hook functions on
---@field functionNames table<number, string> The names of the functions that we want to hook

---@class LibAddonProfilesModule : table
---@field moduleName string The name of the module. This should be the same as the AddOn name but can be different if the AddOn has multiple modules.
---@field icon number | string The icon to use for the module
---@field slash string
---@field needReloadOnImport boolean If the AddOn needs to be reloaded after importing a profile
---@field needProfileKey boolean If importing a profilestring needs a profileKey that is not otherwise encoded in the profileString. Was used by the import anything function, might need again
---@field preventRename boolean For AddOns that have only global profiles, used in the intro wizard
---@field willOverrideProfile boolean If the profile will override the current profile when imported. Also for AddOns that only have global profiles
---@field nonNativeProfileString boolean If the profileString generated by this library is not the same as the profileString used by the AddOn or if the AddOn does not have the concept of profile strings.
---@field isLoaded fun(self: LibAddonProfilesModule) : boolean Check if the AddOn is loaded
---@field needsInitialization fun(self: LibAddonProfilesModule) : boolean Some AddOns need to be initialized before we can access certain interals like the profiles and / or profile keys
---@field openConfig fun(self: LibAddonProfilesModule) : nil Open the AddOn config window
---@field closeConfig fun(self: LibAddonProfilesModule) : nil Close the AddOn config window
---@field getProfileKeys? fun(self: LibAddonProfilesModule,) : table<string, any> A list of profile keys. The values can be anything. If the function is not defined the module has global profiles or no profiles.
---@field getCurrentProfileKey? fun(self: LibAddonProfilesModule,) : string The profile key of the profile that is active on the current character. If the function is not defined the module has global or no profiles.
---@field getProfileAssignments? fun(self: LibAddonProfilesModule) : table<string, string> | nil The key should be in format "Playername - RealmName". The value should be the profile key. A nil return value means that the profile not character specific and can not be directly retrieved. Use WagoUI db to get the profile key. If the function is not defined the module has global profiles.
---@field isDuplicate fun(self: LibAddonProfilesModule, profileKey: string) : boolean Check if a profile with the given key already exists
---@field setProfile? fun(self: LibAddonProfilesModule, profileKey: string) Set the profile to the given profile key. If the function is not defined the module has global profiles or no profiles.
---@field testImport fun(self: LibAddonProfilesModule, profileString: string, profileKey: string | nil, profileData: table| nil, rawData: table | nil, moduleName: string | nil) : string | table | nil Test the profile string to see if it can be imported. Return the profile key if it can, nil otherwise. Tests profileData, rawData, and moduleName if they are provided, otherwise decodes the profileString and tests that.
---@field importProfile fun(self: LibAddonProfilesModule, profileString: string, profileKey: string, fromIntro: boolean) : nil Import the profile string. Does nothing if the module has global profiles.
---@field exportProfile fun(self: LibAddonProfilesModule, profileKey: string | table) : string | table | nil Export the profile string. If the function returns a table it will contain multiple profile strings.
---@field exportOptions table<any, any> | nil A table of options that can be used to customize the export. The options are used in the exportProfile function.
---@field setExportOptions? fun(self: LibAddonProfilesModule, options: table) : nil  Set the export options. The options are used in the exportProfile function.
---@field exportGroup? fun(self: LibAddonProfilesModule, profileKey: string) : string | nil For modules that have a group of export strings, export a single export string of that group. (e.g. WeakAuras)
---@field areProfileStringsEqual fun(self: LibAddonProfilesModule, profileStringA: string | nil, profileStringB: string | nil , tableA : table | nil, tableB : table | nil) : areEqual: boolean, changedEntries: table | nil, removedEntries: table | nil Deep compare two profile strings or two tables.
---@field refreshHookList table<number, RefreshHook> | nil Defines what functions should be hooked when wanting to monitor additions / deletions of profiles and changes to the currently active profile key.

---@type LibAddonProfilesModule
local m = {
  moduleName = "ExampleModule",
  icon = 9999999,
  slash = "/exampleslash",
  needReloadOnImport = false,
  needProfileKey = false,
  preventRename = false,
  willOverrideProfile = false,
  nonNativeProfileString = false,

  isLoaded = function(self)
    local loaded = C_AddOns.IsAddOnLoaded("AddonName")
    return loaded
  end,

  needsInitialization = function(self)
    return false
  end,

  openConfig = function(self)

  end,

  closeConfig = function(self)

  end,

  getProfileKeys = function(self)
    return {
      ["Global"] = true
    }
  end,

  getCurrentProfileKey = function(self)
    return "Global"
  end,

  isDuplicate = function(self, profileKey)
    if not profileKey then return false end
    return self:getProfileKeys()[profileKey] ~= nil
  end,

  setProfile = function(self, profileKey)
    if not profileKey then return end
    if not self:getProfileKeys()[profileKey] then return end
  end,

  testImport = function(self, profileString, profileKey, profileData, rawData, moduleName)
    if not profileString then return end
  end,

  importProfile = function(self, profileString, profileKey, fromIntro)
    if not profileString then return end
  end,

  exportOptions = {
    example = false
  },

  setExportOptions = function(self, options)
    for k, v in pairs(options) do
      self.exportOptions[k] = v
    end
  end,

  exportProfile = function(self, profileKey)
    if not profileKey then return end
    if type(profileKey) ~= "string" then return end
    if not self:getProfileKeys()[profileKey] then return end
  end,

  areProfileStringsEqual = function(self, profileStringA, profileStringB, tableA, tableB)
    if not profileStringA or not profileStringB then return false end
    local _, profileDataA = private:GenericDecode(profileStringA)
    local _, profileDataB = private:GenericDecode(profileStringB)
    if not profileDataA or not profileDataB then return false end
    return private:DeepCompareAsync(profileDataA, profileDataB)
  end,

  refreshHookList = {
    {
      tableFunc = function()
        return ExampleAddon.db
      end,
      functionNames = { "SetProfile", "DeleteProfile" }
    },
  }
}
private.modules[m.moduleName] = m
